_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml

root:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /home
        permanent: true

# VendorProjetimieBundle routes
_imie-project:
    resource: "@VendorProjetimieBundle/Resources/config/routing.yml"

login:
    pattern:   /login
    defaults:  { _controller: VendorProjetUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout