<?php

namespace VendorProjet\imieBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeOfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeOfferRepository extends EntityRepository
{
}
